### ISSUE TITLE
Add Huawei cloud IoT

### ISSUE THREAD

**Issue by ctlove0523** [phodal/awesome-iot#103]

**Comment by aileheart** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ctlove0523** [comment]
see #104

**Comment by aileheart** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
