### ISSUE TITLE
Fix CR/LF issues

### ISSUE THREAD

**Issue by ctron** [phodal/awesome-iot#41]
I think there are currently a few CR/LF line ending issues in the README.md file (maybe other files as well).

Checking out the repository in a Unix-ish system automatically creates changes once a file is opened and saved again, making no modifications.

I would suggest to either enforce the Unix-style line endings, as this works best with Git. Or go for a `.gitattributes` file which might help here.

If you like I can make a PR for this.

**Comment by phodal** [comment]
@ctron feel free to make a PR.
