### ISSUE TITLE
Adding a free book but repo is not maintained for a year

### ISSUE THREAD

**Issue by shantanoo-desai** [phodal/awesome-iot#43]
Should I add a very good book about [IPv6 and Wireless Sensor Networks using Contiki OS](https://github.com/marcozennaro/IPv6-WSN-book) however the last commits have been a year ago.

I understand that software libraries which are not maintained shouldn't be added but what about books?

(info: I already have a fork with the change ready on my local machine, if you agree I can make PR)

**Comment by phodal** [comment]
@shantanoo-desai feel free to give a PR

**Comment by phodal** [comment]
fixed with #44
