### ISSUE TITLE
.NET Core IoT

### ISSUE THREAD

**Issue by rsciriano** [phodal/awesome-iot#88]
Hello, I think it would be interesting to include [.NET Core IoT](https://github.com/dotnet/iot) in this fabulous list

The description could be something like:

> Dotnet IoT is a set of libraries to interact with sensors, displays and input devices from .NET Core framework. 
>This library allows to work with the GPIO port for various boards like Raspberry Pi and Hummingboard and
> it contains a growing set of community-maintained device bindings for IoT components.

In my opinion, it will fit in the framework section

I would be happy to send a pull request :-)

**Comment by phodal** [comment]
just do it~

**Comment by rsciriano** [comment]
@phodal done #89 :-)
