### ISSUE TITLE
Request to add Atman IoT to the list

### ISSUE THREAD

**Issue by kkhoury38** [phodal/awesome-iot#90]
Hi,

Could you please add Atman IoT (https://atman-iot.com) to the platform list?

Atman IoT is an IoT platform focused on IoT solution rapid prototyping, promising to help you build your IoT solution in a week! 
Atman IoT is also available as a self hosted gateway, packaged as stand alone docker container (https://hub.docker.com/r/atmantech/atman-iot). 
Atman IoT offers an extensive API with ready to use, open source connector libraries (https://github.com/kkhoury38/atman-iot-api-connect)

Online Demo: https://atman-iot.com/signup-redirect

Thanks a lot!

Khalil

**Comment by phodal** [comment]
welcome to PR

**Comment by kkhoury38** [comment]
thank you :)
